version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./services/frontend/app-chaldea:/app
    working_dir: /app
    command: sh -c "npm install --legacy-peer-deps"

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend


  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
      build:
        context: .
        dockerfile: ./docker/phpmyadmin/Dockerfile
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        PMA_USER: ${MYSQL_USER}
        PMA_PASSWORD: ${MYSQL_PASSWORD}
      ports:
        - "8081:80"
      depends_on:
        - mysql

  rabbitmq:
    build:
      context: .
      dockerfile: ./docker/rabbitmq/Dockerfile
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
    mysql_data: