FROM rabbitmq:3-management

# Копируем конфигурационные файлы, если они есть
# COPY ./rabbitmq.config /etc/rabbitmq/rabbitmq.config
# COPY ./definitions.json /etc/rabbitmq/definitions.json

# Открываем порты
EXPOSE 5672 15672
